language: python
python: 2.7
env:
  - TOX_ENV=py33
  - TOX_ENV=py32
  - TOX_ENV=py27
  - TOX_ENV=py26
install:
  - pip install tox
  - pip install python-coveralls
  - pip install coveralls
script:
  - tox -e $TOX_ENV
after_success:
  coveralls